unique_ids:
  forms:
    Form1: '1704336268976141947253122.23422'
  modules: {}
  server_modules: {}
  assets:
    js/demo/chart-pie-demo.js: UNVD5OT5VV4I7KTRWGY55CH4VC6ZSGR7
    buttons.html: 2AYNQQTXN3A3UNR55X3YRVTDDJGM66QP
    scss/_global.scss: BOORFRBUDOTUTLUDJK766JPZV6YHPVIR
    scss/_error.scss: CDIN2FCVC3GB4CA6HW4YFGEWDHEKJV67
    scss/_navs.scss: FW6MTR4GU5SJM4AETM2SK46QPMKWTSWR
    utilities-animation.html: XH2TQXXSPDP4IJUHJZID7XL7OHMW6GDQ
    README.md: ADDTHVLLLUHDAUPPVZTBMXYULU7XIZ74
    scss/_variables.scss: TVXS33PQVRXG7MNQB7HO5SYUFKHVXQAT
    theme.css: TKDX5NLLJTDZDOMXE5VPCKYOHXGXG576
    utilities-other.html: XEVZWWVZJ2STMB7W26NO6DCMVTDBZXDH
    scss/navs/_topbar.scss: F6XFSH4CV2ZVGRGWXPLALWA43SQFMBOY
    scss/_buttons.scss: VQC6YQSDHOYJHXHXO2W3FGDETIM2UFGP
    scss/navs/_sidebar.scss: DUSBX7XIT2PNM4RRY7UB7ACKCVNQ2MMD
    scss/_dropdowns.scss: V4JVQ5JCO2F6G6SK32ZHLSFDNOX7LGOY
    scss/sb-admin-2.scss: ZDZEHK636Q6MCU7GZUX2BTFJSA7KP4C4
    scss/utilities/_border.scss: IZWD55ZSCBJSZWD7R3TJ7LSZKA6JGZDJ
    login.html: IR6T74TV5AF3UEGR3XC5ZXUWZ4FDE2AP
    LICENSE: 37IX35DV42QJOJ53GZ3E2AUQTWQ6G7ZH
    404.html: 4CZZCP4PTMP644YY2SB4AJQMDWYLECHN
    scss/_utilities.scss: 3BXKVMPDZYQMVNV27FSIFI4UH357H57W
    utilities-border.html: FJAFMQI4B2X2FBSG45O3AF35W6FLSLZ5
    img/undraw_profile_3.svg: VM3JUR5YUYVMU73IPL5MB2FP2XQMUGVD
    standard-page.html: 2UPCMYKIKMXQJME6Q72DSZPT6PBJZE5L
    css/sb-admin-2.min.css: VSJ6QH2TGUWK5I6SW5CK64REY6HC6NTN
    img/undraw_profile_1.svg: QAS7PP6NS26PPOHYQPD342STEO3TNANO
    scss/utilities/_background.scss: LVS2NHJ56KZZXEF2KOB32PSK66U3RWYG
    tables.html: OZSRVWRNGWQBF7RH5LKZZXGP2IA6BUMO
    img/undraw_rocket.svg: B4HEHE74LVQGMWTTMVJHE33TIJOM57V7
    scss/_cards.scss: L3IVHOKGTA7GCZPRQ3BFHNQT5XFFZIWH
    img/undraw_posting_photo.svg: KI3OVBFFZPSIPUDSZ6FSMPDRDLPYS3MJ
    scss/utilities/_display.scss: PSJZZIP7KNO7ENZHYP6GMHZVTXONFOKZ
    cards.html: ZF5IZIHQUELRYVYLS7J5B43COVIT6MTL
    js/sb-admin-2.js: 4IK6BRLAGMI2LHRXH7R2UUUOZVPXC5W4
    gulpfile.js: B6EIFA4XR24M57Q234D5FBF7EC67HSTA
    scss/navs/_global.scss: DAMQFAHLLV2EMOBTKAAAKBU2ADN4BRQP
    index.html: HG4OHW5FOBLLXVEOVKERMWCVPPNX4NHZ
    PRO_UPGRADE.txt: PAKWMN5DMFTPWTAB73KKY7U554BBCLXG
    scss/_mixins.scss: MXFDBGDT4I3AZDP4NKAXLWZLOFPH3RO4
    scss/_login.scss: M5AHU6CFYNKX4QPMM6UMNBKY5FEXGEUG
    scss/utilities/_animation.scss: VRZBDT2V3UV2X5GHHJ2BRFRZH2P2ITK2
    scss/utilities/_text.scss: NKXJJQRWHP44PTR7VNRT7LNJN7JGOAVE
    blank.html: ASM6VH5XLCKMXRS5KU4JLQL6FITAVUQV
    package.json: JRLVX3HQVNHORODLKEV55DCZ2LGNN7LO
    utilities-color.html: WUOO5C7ERFDHH2ZX5NTVBIKK7GJ7LATS
    js/demo/chart-bar-demo.js: KFKTLV5GKHLCMS4GXLGCR6N7E6XQTBN5
    scss/_charts.scss: DDULQVTIFMN3YK5QWKUVBGOI6GWWD333
    forgot-password.html: 5B2NH446CGG7FJ7KRT7P5BKF3ANNABXE
    css/sb-admin-2.css: CMGJBVUVNQ5XPWCDROCD7JVXYHHKTKIT
    vendor/.gitkeep: '1704337021417390455382683.6078'
    register.html: V53VALSE73H6VF2QVENIIF5KPLTMQKBS
    img/undraw_profile.svg: JJKIU5S4KPM7IHSX7NE5GFHTZTB75J6V
    js/sb-admin-2.min.js: IKPMYRXGAUZJAQJ6D2ZBR76YVUM2HBIR
    scss/utilities/_progress.scss: ZOFIZDLN4A7DYSZBJNDWQUUSGN2XHSXT
    js/demo/chart-area-demo.js: I3BJE7BSYCMI54IEIO2XMQRA4U5S552E
    js/demo/datatables-demo.js: F55G4QIDZ6M752YBK4WFSDN7YHT2R3GA
    charts.html: WU7OITJWGPH22WEK75UBDKCQFNKQVKVR
    img/undraw_profile_2.svg: I7NBH4DEKSHWGHTCIK62RFTBPJMBSJBT
    package-lock.json: IWARYWGIUIXFRTNPNT765AILDZID5OGH
    scss/_footer.scss: TMMBHK5DXG5HAUENI2D6T64GVX5B6MBQ
    scss/utilities/_rotate.scss: E6IE4HZYXWGMLH5MTMEGOGN7JORJZ5UV
